### ISSUE TITLE
image email sharing via SES requires address verification for new addresses

### ISSUE THREAD

**Issue by deepblue-phoenix** [gloflow/gloflow#225]
getting this when trying to send an email to an address for the first time:

"MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-1: *****"

**Comment by kevinmichaelchen** [comment]
is the SES account configured in [_sandbox_ mode](https://stackoverflow.com/questions/37528301/email-address-is-not-verified-aws-ses)?

**Comment by deepblue-phoenix** [comment]
I suspected this was the cause, in the process of getting this enabled and tested. thanks for the suggestion :)
